version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8081:8081"
    volumes:
      - ./:/opt/frontend
    entrypoint: "npm run dev"
